import { createClient } from '@supabase/supabase-js'
import { Sparkles, Users, Activity, BookOpen, Lightbulb, HelpCircle, ArrowLeft } from 'lucide-react'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

// Inicjalizacja klienta tylko jeśli zmienne istnieją, aby uniknąć błędu serwerowego
const supabase = (supabaseUrl && supabaseKey) 
  ? createClient(supabaseUrl, supabaseKey)
  : null

// Fetch summary from Supabase
async function getSummary(slug) {
  if (!supabase) {
    console.error('Supabase client not initialized - missing env vars');
    return null;
  }
  try {
    // 1. Try by direct slug match
    if (!slug) return null;

    let { data: slugData } = await supabase
      .from('summaries')
      .select('id, book_title, content_json')
      .eq('slug', slug)
      .maybeSingle()

    if (slugData) {
      return processData(slugData)
    }

    // 2. Try by ID if it looks like a UUID
    const isUuid = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(slug)
    if (isUuid) {
      let { data: idData } = await supabase
        .from('summaries')
        .select('id, book_title, content_json')
        .eq('id', slug)
        .maybeSingle()
        
      if (idData) return processData(idData)
    }

    // 3. Fallback: Fuzzy search by title (Slug -> Title)
    // "zemsta-fredro" -> "zemsta fredro"
    const titleQuery = slug.replace(/-/g, ' ')
    let { data: titleData } = await supabase
      .from('summaries')
      .select('id, book_title, content_json')
      .ilike('book_title', `%${titleQuery}%`)
      .limit(1)
      .maybeSingle()

    if (titleData) return processData(titleData)

    return null
  } catch (e) {
    console.error('Supabase fetch error:', e)
    return null
  }
}

function processData(record) {
  const json = record.content_json || {}
  
  // Extract teaser from content (keep existing logic for metadata)
  let teaserText = json.seo_description || ''
  
  const summarySection = json.custom_sections?.find(s => s.id === 'summary')
  const summaryContent = summarySection ? summarySection.content : ''

  if (!teaserText) {
    if (summaryContent) {
       teaserText = summaryContent.substring(0, 300) + '...'
    }
  }
  
  if (!teaserText && json.literary_analysis?.context) {
     teaserText = json.literary_analysis.context.substring(0, 200) + '...'
  }
  
  // Clean AI artifacts more thoroughly
  const aiPatterns = [
    /AI generated summary/gi,
    /Generated AI summary/gi,
    /Generated by AI/gi,
    /This summary was generated/gi,
    /Created with AI/gi,
    /Sztuczna inteligencja/gi,
    /Model językowy/gi,
    /Jako AI/gi,
    /Podsumowanie wygenerowane/gi,
    /summary for .* by .*/gi,
    /Oto streszczenie/gi
  ];

  let cleanedSummary = summaryContent;
  let cleanedTeaser = teaserText;

  aiPatterns.forEach(pattern => {
    cleanedSummary = cleanedSummary.replace(pattern, '');
    cleanedTeaser = cleanedTeaser.replace(pattern, '');
  });

  // Remove Markdown headers from content if they leaked in
  cleanedSummary = cleanedSummary.replace(/^#+\s+/gm, '');
  cleanedTeaser = cleanedTeaser.replace(/^#+\s+/gm, '');

  cleanedSummary = cleanedSummary.trim();
  cleanedTeaser = cleanedTeaser.trim();

  const summaryPreview = cleanedSummary.length > 400 
      ? cleanedSummary.substring(0, 400) + '...' 
      : cleanedSummary

  // Process characters (limit to 2 main ones for free view)
  const characters = (json.characters || [])
      .filter(c => c && (c.role === 'Protagonist' || c.role === 'Antagonist'))
      .slice(0, 2)
      .map(c => ({
          name: c.name || 'Nieznany bohater',
          role: c.role || '',
          description: c.description || '',
          icon: c.icon_emoji || ''
      }))

  // Process timeline (limit to 3 events)
  const timeline = (json.timeline || []).slice(0, 3).map(e => ({
      chapter: e.chapter || '',
      event: e.event || '',
      description: e.description || ''
  }))

  return {
    title: json.title || record.book_title,
    author: (json.author_name && json.author_name !== 'asd') ? json.author_name : (record.book_title.includes('(') ? record.book_title.split('(')[1].replace(')', '') : 'Autor nieznany'),
    teaser: cleanedTeaser, // For SEO
    summaryPreview: summaryPreview,
    characters: characters,
    timeline: timeline,
    fullContentId: record.id,
    slug: json.slug || slugify(json.title || record.book_title)
  }
}

async function getRelatedSummaries(currentId) {
  if (!supabase) return [];
  try {
    const { data } = await supabase
      .from('summaries')
      .select('slug, book_title')
      .not('slug', 'is', null)
      .neq('id', currentId)
      .limit(5)
    return data || []
  } catch (e) {
    return []
  }
}

export async function generateMetadata({ params }) {
  const resolvedParams = await params
  const slug = resolvedParams.slug
  const summary = await getSummary(slug)
  if (!summary) return { title: 'Nie znaleziono - Strescto' }
  
  const title = `Streszczenie ${summary.title} - ${summary.author} | Opracowanie, Plan Wydarzeń`;
  const description = `Kompletne opracowanie lektury "${summary.title}" (${summary.author}). Znajdziesz tu szczegółowy plan wydarzeń, charakterystykę bohaterów i najważniejsze motywy literackie. Idealna pomoc w nauce do matury i sprawdzianu.`;
  
  return {
    title,
    description,
    keywords: [`streszczenie ${summary.title}`, `opracowanie ${summary.title}`, `plan wydarzeń ${summary.title}`, `bohaterowie ${summary.title}`, summary.title, summary.author, 'lektura szkolna', 'język polski', 'strescto'],
    alternates: {
      canonical: `https://strescto.pl/s/${slug}`,
    },
    openGraph: {
      title: `Streszczenie i Opracowanie: ${summary.title}`,
      description: `Wszystko co musisz wiedzieć o lekturze "${summary.title}". Plan wydarzeń, postacie i motywy w jednym miejscu.`,
      url: `https://strescto.pl/s/${slug}`,
      siteName: 'Strescto',
      type: 'article',
    },
  }
}

export default async function SummaryPage({ params }) {
  const resolvedParams = await params
  const slug = resolvedParams.slug
  const summary = await getSummary(slug)
  
  if (!summary) {
    return (
      <div style={{ padding: '60px 20px', textAlign: 'center', fontFamily: 'sans-serif', maxWidth: '600px', margin: '0 auto' }}>
        <h1 style={{ marginBottom: '20px', fontSize: '2rem' }}>Nie znaleziono streszczenia</h1>
        <p style={{ fontSize: '1.2rem', marginBottom: '40px', lineHeight: '1.6', color: '#444' }}>
          Jeszcze nie wygenerowaliśmy streszczenia dla tej książki, ale możesz to zrobić w naszej aplikacji w kilka sekund!
        </p>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', alignItems: 'center' }}>
          <a href="https://app.strescto.pl" 
             style={{ 
               backgroundColor: '#000', 
               color: '#fff', 
               padding: '16px 32px', 
               borderRadius: '12px', 
               textDecoration: 'none',
               fontWeight: 'bold',
               fontSize: '18px',
               boxShadow: '0 4px 12px rgba(0,0,0,0.15)'
             }}>
             Otwórz aplikację Streść.to
          </a>
          <a href="/" style={{ color: '#0070f3', marginTop: '20px', textDecoration: 'none' }}>&larr; Wróć na stronę główną</a>
        </div>
      </div>
    )
  }

  const related = await getRelatedSummaries(summary.fullContentId)

  // Schema.org JSON-LD
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Book',
    'name': summary.title,
    'author': {
      '@type': 'Person',
      'name': summary.author
    },
    'description': summary.teaser,
    'workExample': {
      '@type': 'CreativeWork',
      'potentialAction': {
        '@type': 'ReadAction',
        'target': {
          '@type': 'EntryPoint',
          'urlTemplate': `https://strescto.pl/s/${slug}`
        }
      },
      'isAccessibleForFree': 'False',
      'hasPart': {
        '@type': 'WebPageElement',
        'isAccessibleForFree': 'False',
        'cssSelector': '.premium-lock'
      }
    }
  }

  return (
    <div className="summary-page-container" style={{ backgroundColor: '#F2F0E9', minHeight: '100vh', color: '#232323', fontFamily: 'var(--font-manrope), sans-serif', display: 'flex' }}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      
      {/* Sidebar (Desktop) */}
      <aside style={{ 
        width: '300px', 
        position: 'fixed', 
        height: '100vh', 
        borderRight: '1px solid rgba(0,0,0,0.05)', 
        padding: '40px 24px', 
        display: 'none', // Default hidden, handled by media query in global or inline
        flexDirection: 'column',
        backgroundColor: '#fff',
        zIndex: 100
      }} className="sidebar-desktop">
        
        {/* Back Button */}
        <a href="/" style={{ 
          textDecoration: 'none', 
          color: '#5D5D5D', 
          display: 'flex', 
          alignItems: 'center', 
          fontSize: '14px', 
          fontWeight: '600',
          marginBottom: '32px'
        }}>
          <ArrowLeft size={16} style={{ marginRight: '8px' }} /> Wróć
        </a>

        {/* Title & Author */}
        <div style={{ marginBottom: '40px' }}>
          <h1 style={{ 
            fontFamily: 'var(--font-fraunces)', 
            fontSize: '28px', 
            fontWeight: 'bold', 
            color: '#232323', 
            marginBottom: '4px',
            lineHeight: '1.1'
          }}>
            {summary.title}
          </h1>
          <p style={{ fontSize: '14px', color: '#888', fontWeight: '500' }}>{summary.author}</p>
        </div>

        {/* Navigation */}
        <nav style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '24px' }}>
          
          {/* Overview Group */}
          <div>
            <div style={{ fontSize: '11px', textTransform: 'uppercase', color: '#999', letterSpacing: '1px', marginBottom: '12px', fontWeight: 'bold' }}>overview</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
               <div style={{ 
                 padding: '10px 16px', 
                 backgroundColor: '#FFF0EE', 
                 color: '#E05D44', 
                 borderRadius: '12px', 
                 fontWeight: 'bold', 
                 fontSize: '14px',
                 display: 'flex',
                 alignItems: 'center',
                 justifyContent: 'space-between'
               }}>
                 <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                   <Sparkles size={18} /> Streszczenie
                 </span>
                 <span style={{ width: '6px', height: '6px', backgroundColor: '#E05D44', borderRadius: '50%' }}></span>
               </div>
               
               <a href={`https://app.strescto.pl/login?redirect=/book/${summary.fullContentId}`} style={{ padding: '10px 16px', color: '#5D5D5D', textDecoration: 'none', fontSize: '14px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                 <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                   <Users size={18} /> Postacie
                 </span>
                 <span style={{ color: '#999' }}><HelpCircle size={14} /></span>
               </a>
               
               <a href={`https://app.strescto.pl/login?redirect=/book/${summary.fullContentId}`} style={{ padding: '10px 16px', color: '#5D5D5D', textDecoration: 'none', fontSize: '14px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                 <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                   <Activity size={18} /> Plan Wydarzeń
                 </span>
                 <span style={{ color: '#999' }}><HelpCircle size={14} /></span>
               </a>
            </div>
          </div>

          {/* Analysis Group */}
          <div>
             <div style={{ fontSize: '11px', textTransform: 'uppercase', color: '#999', letterSpacing: '1px', marginBottom: '12px', fontWeight: 'bold' }}>Analiza</div>
             <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <a href={`https://app.strescto.pl/login?redirect=/book/${summary.fullContentId}`} style={{ padding: '10px 16px', color: '#5D5D5D', textDecoration: 'none', fontSize: '14px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <Lightbulb size={18} /> Motywy i Wątki
                  </span>
                  <span style={{ fontSize: '12px' }}>🔒</span>
                </a>
                <a href={`https://app.strescto.pl/login?redirect=/book/${summary.fullContentId}`} style={{ padding: '10px 16px', color: '#5D5D5D', textDecoration: 'none', fontSize: '14px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <BookOpen size={18} /> Analiza Literacka
                  </span>
                  <span style={{ fontSize: '12px' }}>🔒</span>
                </a>
             </div>
          </div>

           {/* Extras Group */}
           <div>
             <div style={{ fontSize: '11px', textTransform: 'uppercase', color: '#999', letterSpacing: '1px', marginBottom: '12px', fontWeight: 'bold' }}>extras</div>
             <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <a href={`https://app.strescto.pl/login?redirect=/book/${summary.fullContentId}`} style={{ padding: '10px 16px', color: '#5D5D5D', textDecoration: 'none', fontSize: '14px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <HelpCircle size={18} /> Quizy
                  </span>
                  <span style={{ fontSize: '12px' }}>🔒</span>
                </a>
             </div>
          </div>

        </nav>

        {/* Recommended Analysis (Banner) */}
        {related.length > 0 && (
          <div style={{ marginTop: 'auto', paddingTop: '20px' }}>
             <div style={{ fontSize: '10px', textTransform: 'uppercase', color: '#999', letterSpacing: '1px', marginBottom: '12px', fontWeight: 'bold' }}>INNE OPRACOWANIA</div>
             <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
               {related.map((item, idx) => (
                   <a 
                     key={idx} 
                     href={`/s/${item.slug}`} 
                     style={{ 
                       textDecoration: 'none', 
                       display: 'flex', 
                       alignItems: 'center', 
                       gap: '8px',
                       color: '#232323',
                       transition: 'color 0.2s ease'
                     }}
                   >
                     <span style={{ color: '#E05D44' }}><Sparkles size={14} /></span>
                     <span style={{ fontSize: '12px', fontWeight: '600', color: 'inherit' }}>{item.book_title}</span>
                   </a>
                 ))}
             </div>
          </div>
        )}
      </aside>

      {/* Main Content Area */}
      <main className="main-content">
        
        {/* Intro Paragraph */}
        <div style={{ fontSize: '18px', lineHeight: '1.8', color: '#232323', marginBottom: '48px' }}>
          <p style={{ fontWeight: '400' }}>
            {summary.teaser || `Odkryj kompletne opracowanie lektury "${summary.title}". Poniżej znajdziesz najważniejsze informacje, charakterystykę kluczowych postaci oraz szczegółowy plan wydarzeń, który pomoże Ci lepiej zrozumieć fabułę i motywy utworu.`}
          </p>
        </div>

        {/* Characters Section */}
        <section style={{ marginBottom: '56px' }}>
          <h2 style={{ fontSize: '28px', fontFamily: 'var(--font-fraunces)', fontWeight: 'bold', marginBottom: '24px', color: '#232323' }}>
            Główne postacie
          </h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
             {summary.characters.map((char, i) => (
               <li key={i} style={{ marginBottom: '20px', fontSize: '17px', lineHeight: '1.7', color: '#232323', display: 'flex', alignItems: 'flex-start' }}>
                 <span style={{ marginRight: '12px', marginTop: '10px', width: '6px', height: '6px', backgroundColor: '#E05D44', borderRadius: '50%', flexShrink: 0 }}></span>
                 <span>
                   <strong style={{ fontWeight: '700' }}>{char.name}</strong>: {char.description}
                 </span>
               </li>
             ))}
             <li style={{ marginTop: '24px' }}>
                <a href={`https://app.strescto.pl/login?redirect=/book/${summary.fullContentId}`} style={{ color: '#E05D44', fontWeight: 'bold', textDecoration: 'none', fontSize: '15px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <span>+ Zobacz pozostałe postacie w aplikacji</span>
                </a>
             </li>
          </ul>
        </section>

        {/* Summary Content Section */}
        <section style={{ marginBottom: '60px' }}>
          <h2 style={{ fontSize: '28px', fontFamily: 'var(--font-fraunces)', fontWeight: 'bold', marginBottom: '24px', color: '#232323' }}>
            Szczegółowe streszczenie fabuły
          </h2>
          
          <div style={{ position: 'relative' }}>
             <div style={{ fontSize: '17px', lineHeight: '1.8', color: '#232323' }}>
                <div dangerouslySetInnerHTML={{ __html: summary.summaryPreview.replace(/\n/g, '<br/><br/>') }} />
             </div>
             
             {/* Fade Out Overlay */}
             <div style={{ 
                position: 'absolute',
                bottom: 0,
                left: 0,
                right: 0,
                height: '200px',
                background: 'linear-gradient(to bottom, rgba(242,240,233,0) 0%, rgba(242,240,233,1) 90%)',
                zIndex: 5
              }}>
             </div>
          </div>
          
          {/* Client Side Auth & CTA */}
          <SummaryClient 
            teaser={summary.teaser} 
            fullContentId={summary.fullContentId} 
            isPremium={true} // Tutaj można by wstawić logikę sprawdzającą czy to premium z bazy
          />
        </section>

        {/* FAQ / SEO Section */}
        <section style={{ borderTop: '1px solid rgba(0,0,0,0.05)', paddingTop: '40px' }}>
           <h2 style={{ fontSize: '22px', fontFamily: 'var(--font-fraunces)', fontWeight: 'bold', marginBottom: '20px' }}>Często zadawane pytania</h2>
           <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
              <div>
                 <h4 style={{ fontWeight: 'bold', marginBottom: '8px' }}>Czy to streszczenie zawiera wszystkie rozdziały?</h4>
                 <p style={{ fontSize: '15px', color: '#5D5D5D' }}>Tak, w pełnej wersji aplikacji znajdziesz szczegółowy opis każdego rozdziału oraz kluczowych wydarzeń.</p>
              </div>
              <div>
                 <h4 style={{ fontWeight: 'bold', marginBottom: '8px' }}>Czy opracowanie jest zgodne z podstawą programową?</h4>
                 <p style={{ fontSize: '15px', color: '#5D5D5D' }}>Nasze materiały są przygotowywane pod kątem wymagań maturalnych i egzaminu ósmoklasisty.</p>
              </div>
           </div>
        </section>

      </main>

      <style dangerouslySetInnerHTML={{ __html: `
        .sidebar-desktop { display: flex !important; }
        .main-content { flex: 1; marginLeft: 300px; maxWidth: 100%; padding: 60px 80px; }
        
        @media (max-width: 1024px) {
          .main-content { padding: 40px 40px !important; }
        }
        @media (max-width: 768px) {
          .sidebar-desktop { display: none !important; }
          .main-content { margin-left: 0 !important; padding: 32px 20px !important; }
          .summary-page-container h1 { font-size: 32px !important; }
          .summary-page-container h2 { font-size: 24px !important; }
        }
      `}} />
    </div>
  )
}
